### ISSUE TITLE
У сайта есть json api?

### ISSUE THREAD

**Issue by agutikov** [minsk-hackerspace/hspace#35]
Судя по коду в 
app/controllers/projects_controller.rb
и наличию 
app/views/projects/index.json.jbuilder
можно предположить что у сайта есть json api.

Но оно не работает. Например 
http://hackerspace.by/projects.json
который должен (по идее) выдавать список проектов
возвращает
{"status":"500","error":"Internal Server Error"}
Т.е. сам рендер в json работает, но возвращается ошибка, а не данные.

**Comment by che** [comment]
а в routes.rb всё верно?



2015-02-25 12:47 GMT+03:00 Alex Gutikov <notifications@github.com>:

> Судя по коду в
> app/controllers/projects_controller.rb
> и наличию
> app/views/projects/index.json.jbuilder
> можно предположить что у сайта есть json api.
>
> Но оно не работает. Например
> http://hackerspace.by/projects.json
> который должен (по идее) выдавать список проектов
> возвращает
> {"status":"500","error":"Internal Server Error"}
> Т.е. сам рендер в json работает, но возвращается ошибка, а не данные.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minsk-hackerspace/hspace/issues/35>.
>



-- 
with best regards,
pavel  chebotarev.

e-mail: info@chepava.by
mob. tel.: +375 29 3179210
mob. tel.: +375 33 3139210

minsk, belarus
http://chepava.by

**Comment by yahor** [comment]
@agutikov 
па джэйсону даступна толькі
http://localhost:3002/spaceapi.json  верне:

{"api":"0.13","space":"Minsk Hackerspace","logo":"http://hackerspace.by/images/default.png","url":"http://hackerspace.by","location":{"address":"Basement near the entrance 3, Bjady 45, Minsk, Belarus","lon":27.59749,"lat":53.94287},"contact":{"facebook":"https://www.facebook.com/hs.minsk","irc":"irc://irc.bynets.org/#hackerspace","ml":"hackerspace-minsk@googlegroups.com"},"issue_report_channels":["ml"],"state":{"open":null},"projects":["http://hackerspace.by/projects/","https://github.com/minsk-hackerspace/"]}

такога роўта няма. то бок будзе памылка. 
http://hackerspace.by/projects.json

**Comment by yahor** [comment]
Fix: https://github.com/minsk-hackerspace/hspace/pull/36

**Comment by yahor** [comment]
@k2m30 @jekhor падправіў. пасля дэплоя можна закрываць, калі працуе джэйсон на праектах

**Comment by k2m30** [comment]
я не карыстаю json на праекце. можа трэба якія тэсты напісаць?

**Comment by yahor** [comment]
тэсты ў працэссе. трэба мне знайсці больш часу каб дапісаць рспекі і зрабіць пул рэквест...
